#!/bin/bash

set +e
cd ~/

function close () {
	rm -f shuftiTempyTemp.temp
	cd - &> /dev/null
}

curl -s -L https://raw.githubusercontent.com/Ajibaji/mr-shufti/master/main -o shuftiTempyTemp.temp

trap close 0 1 2 3 6 9 15
source shuftiTempyTemp.temp
